name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: selene-c0c22
  SERVICE_NAME: selene-app
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Enable APIs
      run: |
        gcloud services enable cloudbuild.googleapis.com
        gcloud services enable run.googleapis.com

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --project ${{ env.PROJECT_ID }} \
          --region ${{ env.REGION }} \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --set-env-vars FIREBASE_PROJECT_ID=selene-c0c22 \
          --set-env-vars FIREBASE_CLIENT_EMAIL=firebase-adminsdk-uwj9y@selene-c0c22.iam.gserviceaccount.com \
          --set-env-vars FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}" \
          --allow-unauthenticated